//import 'dart:convert';
//import 'package:bloc_network_example/models/fact.dart';
//import 'package:http/http.dart' as http;
//
//class FactProvider {
//  // http://jsonplaceholder.typicode.com/users
//
//  Future<List<Autogenerated>> getFact() async {
//    final response = await http.get('https://catfact.ninja/facts?limit=2');
//
//    if (response.statusCode == 200) {
//      final List<dynamic> userJson = json.decode(response.body);
//      return userJson.map((json) => Autogenerated.fromJson(json)).toList();
//    } else {
//      throw Exception('Error fetching users');
//    }
//  }
//}
