//
//class Autogenerated {
//  List<Fact> data;
//
//  Autogenerated({this.data});
//
//  // ignore: missing_return
//  factory Autogenerated.fromJson(Map<String, dynamic> json) {
//    if (json['data'] != null) {
//      Autogenerated(data: json['data']);
//    }
//    return Autogenerated(data: json['data']);
//  }
//}
//
//class Fact {
//  String fact;
//
//  Fact({this.fact});
//
//  factory Fact.fromJson(Map<String, dynamic> json) {
//    return Fact(fact: json['fact']);
//  }
//}
